version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "localize-serverless-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jcz2tbdxpcqi"
s3_prefix = "localize-serverless-aws"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
