name: Push to Main (Deploy to Production)

on:
  push:
    branches:
      - main

jobs:
  call-lint-and-test-workflow:
    uses: ./.github/workflows/lint-and-test.yml

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
